# Generated by Django 5.2.3 on 2025-06-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
