# Generated by Django 5.2.3 on 2025-06-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
