# Generated by Django 5.2.3 on 2025-06-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_item_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryadjustment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
