# Generated by Django 5.2.3 on 2025-06-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryadjustment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='reason',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('STOCK_COUNT', 'Stock Count'), ('OTHER', 'Other')], default='Stock Count', max_length=100),
        ),
    ]
