# Generated by Django 5.2.3 on 2025-06-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventoryadjustment_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cost_price',
            new_name='purchase_price',
        ),
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='reason',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('STOCK_COUNT', 'Stock Count'), ('OTHER', 'Other')], default='STOCK_COUNT', max_length=100),
        ),
    ]
