# Generated by Django 5.2.3 on 2025-06-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_cost_price_item_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='reason',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('STOCK_COUNT', 'Stock Count'), ('STOLEN', 'Stolen Goods'), ('DAMAGED', 'Damaged Goods'), ('OTHER', 'Other')], default='STOCK_COUNT', max_length=100),
        ),
    ]
