# Generated by Django 5.2.3 on 2025-06-20 16:16

import inventory.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventoryadjustment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to=inventory.utils.item_image_upload_path),
        ),
    ]
