# Generated by Django 5.2.3 on 2025-07-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_itemimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_stock',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
