# Generated by Django 5.2.3 on 2025-07-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_item_current_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
    ]
