# Generated by Django 5.2.3 on 2025-07-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_item_current_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='track_inventory',
        ),
    ]
