# Generated by Django 5.2.3 on 2025-07-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_inventoryadjustment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
