# Generated by Django 5.2.3 on 2025-07-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_unitofmeasure_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.unitofmeasure'),
        ),
    ]
