# Generated by Django 5.2.3 on 2025-07-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_inventoryadjustment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryadjustment',
            name='reason',
            field=models.CharField(choices=[('', '-'), ('PURCHASE', 'Purchase (Increase)'), ('STOCK_COUNT_INCREASE', 'Stock Count (Increase)'), ('OTHER_INCREASE', 'Other (Increase)'), ('SALE', 'Sale (Decrease)'), ('STOCK_COUNT_DECREASE', 'Stock Count (Decrease)'), ('STOLEN', 'Stolen Goods (Decrease)'), ('DAMAGED', 'Damaged Goods (Decrease)'), ('OTHER_DECREASE', 'Other (Decrease)')], default='STOCK_COUNT', max_length=100),
        ),
    ]
