# Generated by Django 5.2.3 on 2025-07-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
