# Generated by Django 5.2.3 on 2025-07-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='discount',
        ),
    ]
